Updated prism-benchmark script.

diff --git a/prism-benchmark b/prism-benchmark
--- a/prism-benchmark
+++ b/prism-benchmark
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+# Catch Ctrl-C
+trap control_c SIGINT
+control_c()
+{
+  echo Exiting
+  exit $?
+}
+
 # Process any switches
 while [[ "$1" =~ "^-.+" ]]; do
 	arg="$1"
@@ -74,22 +82,46 @@ if [ "$1" = "" ]; then
 	exit
 fi
 
-# Get property/properties and working directory
-# If arg is a directory, find all pctl/csl files
+# Get working directory and properties
 # (NB: this curently breaks if there are spaces in file/dir names)
 if [ -d "$1" ]; then
-	PRISM_PROPERTIES=( $(find "$1" -name '*.pctl' -o -name '*.csl') )
-	#for PRISM_PROPERTY in "${PRISM_PROPERTIES[@]}"; do
-	#	echo $PRISM_PROPERTY
-	#done
 	PRISM_THIS_DIR="$1"
+	# Read properties in from props file, if exists
+	if [ -e "$PRISM_THIS_DIR"/props ]; then
+		echo Reading properties from "$PRISM_THIS_DIR"/props
+		PRISM_PROPERTIES_LIST_FILE="$PRISM_THIS_DIR"/props
+	fi
+	if [ -e "$PRISM_PROPERTIES_LIST_FILE" ]; then
+		unset PRISM_PROPERTIES
+		count=0
+		while read -r line ; do
+			if [ "$line" != "" ]; then
+				if [[ ! ( "$line" =~ "#.+" ) ]]; then
+					PRISM_PROPERTIES[count]="$line"
+					#echo $count: $line
+					let count=$count+1
+				fi
+			fi
+		done < "$PRISM_PROPERTIES_LIST_FILE"
+	else
+		echo Searching for properties in "$1"
+		PRISM_PROPERTIES=( $(cd "$PRISM_THIS_DIR"; /bin/ls -1 *.pctl *.csl 2> /dev/null) )
+		#PRISM_PROPERTIES=( $(find "$1" -name '*.pctl' -o -name '*.csl') )
+		#for PRISM_PROPERTY in "${PRISM_PROPERTIES[@]}"; do
+		#	echo $PRISM_PROPERTY
+		#done
+	fi
 else
+	PRISM_THIS_DIR=`dirname "$1"`
 	PRISM_PROPERTIES=("$1")
 	if [ ! -e "$1" ]; then
 	 echo Error: Property \"$1\" does not exist
 	 exit
 	fi
-	PRISM_THIS_DIR=`dirname "$1"`
+fi
+if [ ${#PRISM_PROPERTIES[*]} = 0 ]; then
+	echo "Error: No properties found."
+	exit
 fi
 shift
 
@@ -101,6 +133,8 @@ fi
 
 # Loop through properties...
 for PRISM_PROPERTY in "${PRISM_PROPERTIES[@]}"; do
+echo Property: "$PRISM_PROPERTY"
+PRISM_PROPERTY_FILE="$PRISM_THIS_DIR"/"$PRISM_PROPERTY"
 
 # Read models dir in from file (or use cwd)
 if [ -e "$PRISM_THIS_DIR"/models_dir ]; then
@@ -144,22 +178,24 @@ fi
 
 # Read any extra args in from file
 if [ -e "$PRISM_THIS_DIR"/args ]; then
+	echo Reading args from "$PRISM_THIS_DIR"/args
 	BASE_PRISM_ARGS=`cat "$PRISM_THIS_DIR"/args`
 else
 	BASE_PRISM_ARGS=""
 fi
 
 # Loop through models
-echo "$PRISM_THIS_DIR"/
+#echo "$PRISM_THIS_DIR"/
 for PRISM_MODEL in "${PRISM_MODELS[@]}"; do
+echo Model: "$PRISM_MODEL"
 
 	PRISM_MODEL_FILE="$PRISM_MODEL_DIR"/"$PRISM_MODEL"
 	PRISM_MODEL_DIR_NAME="`readlink -e $PRISM_MODEL_DIR | xargs basename`"
-	if [ "$PRISM_PROPERTY" != "" ]; then
-		PRISM_PROPERTY_NAME=`basename $PRISM_PROPERTY`
-	else
-		PRISM_PROPERTY_NAME=""
-	fi
+	#if [ "$PRISM_PROPERTY" != "" ]; then
+	#	PRISM_PROPERTY_NAME=`basename $PRISM_PROPERTY`
+	#else
+	#	PRISM_PROPERTY_NAME=""
+	#fi
 
 	# Loop through arguments array...
 	for PRISM_ARGS in "${PRISM_ARGS_ARRAY[@]}"; do
@@ -168,16 +204,17 @@ for PRISM_MODEL in "${PRISM_MODELS[@]}"; do
 		if [ "$PRISM_LOG_DIR" != "" ]; then
 			# Build name for log file
 			PRISM_LOG_FILE_MODEL="`echo "$PRISM_MODEL" | sed 's/[^a-zA-Z0-9_ \.]//g' | sed 's/-const//g' | sed 's/ \+/\./g' | sed 's/\.\.\///g' | sed 's/\//_/g'`"
+			PRISM_LOG_FILE_PROPERTY="`echo "$PRISM_PROPERTY" | sed 's/[^a-zA-Z0-9_ \.]//g' | sed 's/-const//g' | sed 's/ \+/\./g' | sed 's/\.\.\///g' | sed 's/\//_/g'`"
 			PRISM_LOG_FILE_ARGS="`echo $PRISM_ARGS $@ | sed 's/[^a-zA-Z0-9_ ]//g' | sed 's/ \+/\./g'`"
 			if [ "$PRISM_LOG_FILE_ARGS" != "" ]; then
 				PRISM_LOG_FILE_EXT=".$PRISM_LOG_FILE_ARGS"
 			else
 				PRISM_LOG_FILE_EXT=""
 			fi
-			PRISM_LOG_FILE="$PRISM_LOG_DIR"/"$PRISM_MODEL_DIR_NAME"."$PRISM_LOG_FILE_MODEL"."$PRISM_PROPERTY_NAME""$PRISM_LOG_FILE_EXT.log"
-			$PRISM $PRISM_MODEL_FILE $PRISM_PROPERTY $BASE_PRISM_ARGS $PRISM_ARGS "$@" >& $PRISM_LOG_FILE
+			PRISM_LOG_FILE="$PRISM_LOG_DIR"/"$PRISM_MODEL_DIR_NAME"."$PRISM_LOG_FILE_MODEL"."$PRISM_LOG_FILE_PROPERTY""$PRISM_LOG_FILE_EXT.log"
+			$PRISM $PRISM_MODEL_FILE $PRISM_PROPERTY_FILE $BASE_PRISM_ARGS $PRISM_ARGS "$@" &> $PRISM_LOG_FILE
 		else
-			$PRISM $PRISM_MODEL_FILE $PRISM_PROPERTY $BASE_PRISM_ARGS $PRISM_ARGS "$@"
+			$PRISM $PRISM_MODEL_FILE $PRISM_PROPERTY_FILE $BASE_PRISM_ARGS $PRISM_ARGS "$@"
 		fi
 		
 	done # args list loop
@@ -185,4 +222,5 @@ for PRISM_MODEL in "${PRISM_MODELS[@]}"; do
 done # model loop
 
 done # property loop
+
 
